# nginx proxy address - http://172.17.0.1:59035

name: keycloak
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-app
    domainname: ${BASE_DOMAIN_NAME:-example.com}
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    command: start --proxy-headers=xforwarded
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      KC_HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${APP_ADMIN_USER:-kcadmin}@${BASE_DOMAIN_NAME:-${BASE_HOST_NAME}}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_DB: postgres
      KC_DB_USERNAME: ${DB_USER_NAME:-keycloak}
      KC_DB_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${DB_CREATE_DATABASE_NAME:-keycloak}
      CONTAINER_NAME: keycloak-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:59035:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keycloak
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://keycloak-app:8080'
      - 'cloudflare.hostname=keycloak.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.keycloak-app.entrypoints=http'
      - 'traefik.http.routers.keycloak-app-secure.tls=true'
      - 'traefik.http.routers.keycloak-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.keycloak-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.keycloak-app.middlewares=keycloak-app-https-redirect'
      - 'traefik.http.routers.keycloak-app-secure.entrypoints=https'
      - 'traefik.http.routers.keycloak-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.keycloak-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.keycloak-app-secure.service=keycloak-app'
      - 'traefik.http.services.keycloak-app.loadbalancer.server.port=8080'

  db:
    image: postgres:latest
    container_name: keycloak-db
    hostname: keycloak-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-keycloak}
      POSTGRES_USER: ${DB_USER_NAME:-keycloak}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      CONTAINER_NAME: keycloak-db
    volumes:
      - './volumes/data/db/postgres/keycloak:/var/lib/postgresql/data'
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak

networks:
  keycloak:
    name: keycloak
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
